version: '3.7'
services:
  squid:
    image: squid:latest
    ports:
      - "3128:3128"
    volumes:
      - ./docker/squid/cache:/var/spool/squid
      - ./conf.d:/etc/squid/conf.d
    restart: always